[package]
name = "kraftpunkt-ltu"
version = "0.3.2"
entrypoint = "src/ltu-theme.typ"
authors = ["<@onsdagens>", "<@tim-ufer>", "<@mxmxchere>"]
license = "MIT AND Apache-2.0"
description = "Official presentations at Lule√• University of Technology."
categories = ["presentation"]
repository = "https://github.com/onsdagens/ltu-beamer-template-typst"

[template]
path = "example"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"

