[package]
name = "scholarly-ltupresentation"
version = "0.4.0"
entrypoint = "src/ltu-theme.typ"
authors = ["<@onsdagens>", "<@tim-ufer>", "<@mxmxchere>"]
license = "MIT AND Apache-2.0"
description = "Presentations at Lule√• University of Technology."
categories = ["presentation"]
repository = "https://github.com/onsdagens/scholarly-ltupresentation"

[template]
path = "example"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"

