name: Build Example PDF

on:
  release:
    types: [created]

jobs:
  compile-and-upload:
    name: Compile PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install typst
        run: cargo install typst-cli@0.14.0

      - name: Compile
        run: typst comile example.typ
      
      - name: Upload Release Binary
        uses: softprops/action-gh-release@v2
        with:
          files: example.pdf
