name: Build Example PDF
permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  compile-and-upload:
    name: Compile PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install typst
        run: wget -O - https://github.com/typst/typst/releases/download/v0.14.1/typst-x86_64-unknown-linux-musl.tar.xz | tar xvJ
    
      - name: Download dubious .exe from the internet (Arial font)
        run: wget http://downloads.sourceforge.net/corefonts/arial32.exe

      - name: Extract dubious .exe from the internet
        run: 7z x arial32.exe

      - name: Create local package registry
        run: mkdir -p ~/.local/share/typst/packages/local/kraftpunkt-ltu/

      - name: Link to local package registry
        run: ln -s $(pwd) ~/.local/share/typst/packages/local/kraftpunkt-ltu/0.3.1

      - name: Init template
        run: typst-x86_64-unknown-linux-musl/typst init @local/kraftpunkt-ltu:0.3.1

      - name: Compile
        run: typst-x86_64-unknown-linux-musl/typst compile kraftpunkt-ltu/main.typ ./main.pdf
        env:
          TYPST_FONT_PATHS: ./
      
      - name: Upload Release Binary
        uses: softprops/action-gh-release@v2
        with:
          files: main.pdf

