name: Build Example PDF
permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  compile-and-upload:
    name: Compile PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install typst
        run: wget -O - https://github.com/typst/typst/releases/download/v0.14.0/typst-x86_64-unknown-linux-musl.tar.xz | tar xvJ

      - name: Compile
        run: typst-x86_64-unknown-linux-musl/typst compile example.typ
      
      - name: Upload Release Binary
        uses: softprops/action-gh-release@v2
        with:
          files: example.pdf

